/** Declaration file generated by dts-gen */
declare module "microdata-node" {
  export function toJson(microdataHtml: any, config: any): any;

  export function toJsonld(microdataHtml: any, config: any): any;
}
